### ISSUE TITLE
README examples fail

### ISSUE THREAD

**Issue by wiseman** [gilesc/stanford-corenlp#3]
From the README:
```
core> (corenlp/pos-tag (corenlp/tokenize "Colorless green ideas sleep furiously."))
IOException Unable to resolve "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as either class path, filename or URL  edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem (IOUtils.java:434)
```

and
```
mefingram2.core> (corenlp/parse (corenlp/tokenize "I like cheese."))
NullPointerException   clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:26)
```

and

```
mefingram2.core> (corenlp/dependency-graph "I like cheese")
#loom.graph.SimpleDigraph{:nodeset #{}, :adj {}, :in {}}
```

**Comment by eerohele** [comment]
For posterity, `dependency-graph` seems to work if you give it a `DependencyParse` instead of a string:

```clojure
user=> (pprint (dependency-graph (dependency-parse (parse (tokenize "I like cheese.")))))
{:nodeset #{0 -1 1 2},
 :adj {-1 #{1}, 1 #{0 2}},
 :in {2 #{1}, 1 #{-1}, 0 #{1}},
 :attrs
 {3 {:tag ".", :word "."},
  2 {:tag "NN", :word "cheese"},
  0 {:tag "PRP", :word "I"},
  -1 {:loom.attr/edge-attrs {1 {:type :root}}},
  1
  {:tag "VBP",
   :word "like",
   :loom.attr/edge-attrs {2 {:type :dobj}, 0 {:type :nsubj}}}}}
```

**Comment by wiseman** [comment]
I suppose a pull request to fix the README would help posterity even more... Maybe I can even do it, if the consensus is that the example is simply wrong.

**Comment by gilesc** [comment]
OK, these problems should all now be fixed, however I cannot reproduce the problem with tagging. On my OS (Arch Linux x64, JDK 8), it works out of the box with no additional Maven download required.

Sorry about all the bugs :( I had no idea this repo would be used by people, so the README was actually a sketch of things that should eventually work rather than those that in fact did. Bad, I know. Feel free to reopen if you continue to have similar problems.

**Comment by eerohele** [comment]
FWIW, all of the examples in the README now work for me on OS X 10.10.2, JDK8.

Thanks!
